steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [
      'gcloud', 'functions', 'deploy', 'save-data', '--source', 'save_data', '--entry-point', 'save_data',
      '--runtime', 'python39', '--env-vars-file', 'env.yaml'
  ]
  timeout: '600s'
