steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'function', 'deploy', 'actions']
  dir: 'actions'
  timeout: '600s'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'function', 'deploy', 'actions-data']
  dir: 'actions'
  timeout: '600s'
