steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [
      'gcloud', 'functions', 'deploy', 'actions', '--source', 'actions', '--entry-point', 'process',
      '--runtime', 'python39', '--env-vars-file', 'env.yaml'
  ]
  timeout: '600s'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [
      'gcloud', 'functions', 'deploy', 'actions-data', '--source', 'actions', '--entry-point', 'process',
      '--runtime', 'python39', '--env-vars-file', 'env.yaml'
  ]
  waitFor: ['-']  # The '-' indicates that this step begins immediately.
  timeout: '600s'
